name: 01-wallet-tonweb

on:
  schedule:
    - cron:  '0 8 2 * *'
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: cd 01-wallet/test/tonweb && index.sh